import { Geist, Geist_Mono } from "next/font/google";
import { Inknut_Antiqua } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inknut = Inknut_Antiqua({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // choose what you need
  variable: "--font-inknut",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inknut.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
