import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Inknut_Antiqua } from "next/font/google";

const inknut = Inknut_Antiqua({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-inknut", // creates a CSS variable
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const local = localFont({
  src: [
    {
      path: "../fonts/InknutAntiqua-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-local",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inknut.variable}>
      <body className={`${inknut.variable}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
